// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEga6kq6UZEWV_amrKTVIkNQrGTSPufnQ',
    appId: '1:605689966498:web:3073d276bae19b4f6eccfb',
    messagingSenderId: '605689966498',
    projectId: 'fsm-employee',
    authDomain: 'fsm-employee.firebaseapp.com',
    storageBucket: 'fsm-employee.appspot.com',
    measurementId: 'G-73PZTDWSYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtyaJqKaijCqzQTC5BTlbCWK6gUeh2eSc',
    appId: '1:605689966498:android:3538e05132dc78276eccfb',
    messagingSenderId: '605689966498',
    projectId: 'fsm-employee',
    storageBucket: 'fsm-employee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAswv_sHXN81dt80RUbDJT5aYcPbc3PSV8',
    appId: '1:605689966498:ios:6ce28c80580d85306eccfb',
    messagingSenderId: '605689966498',
    projectId: 'fsm-employee',
    storageBucket: 'fsm-employee.appspot.com',
    iosClientId: '605689966498-ifoeddrovb6llbar4a05cp43ibj3h0ca.apps.googleusercontent.com',
    iosBundleId: 'com.fsm.fsmEmployee',
  );
}
